### Libraries:

In [2]:
import numpy as np
import pandas as pd
import ast

In [3]:
pd.set_option('display.max_columns', None)

#### Data Loading:

In [4]:
movies = pd.read_csv("Datasets/tmdb_5000_movies.csv")
credits = pd.read_csv("Datasets/tmdb_5000_credits.csv")

In [5]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [6]:
movies.shape

(4803, 20)

In [7]:
credits.shape

(4803, 4)

#### Merging:

In [8]:
movies = movies.merge(credits,on="title")
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [9]:
movies['production_companies'][0]

'[{"name": "Ingenious Film Partners", "id": 289}, {"name": "Twentieth Century Fox Film Corporation", "id": 306}, {"name": "Dune Entertainment", "id": 444}, {"name": "Lightstorm Entertainment", "id": 574}]'

In [10]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

#### Selecting Main Features:

In [11]:
movies = movies [
    [
    "movie_id", "title", "overview", "genres", "budget", "cast", 
    "crew", "original_language", 'production_countries',
    "production_companies", "release_date", "revenue", "runtime", 
    "vote_average", "vote_count"
]
    ]
movies.head()

,movie_id,title,overview,genres,budget,cast,crew,original_language,production_countries,production_companies,release_date,revenue,runtime,vote_average,vote_count
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",237000000,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",en,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""name"": ""Ingenious Film Partners"", ""id"": 289...",2009-12-10,2787965087,162.0,7.2,11800
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",300000000,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",en,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",2007-05-19,961000000,169.0,6.9,4500
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",245000000,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",en,"[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...","[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",2015-10-26,880674609,148.0,6.3,4466
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",250000000,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",en,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",2012-07-16,1084939099,165.0,7.6,9106
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",260000000,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",en,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",2012-03-07,284139100,132.0,6.1,2124

#### Removing Null Values:

In [12]:
movies.isnull().sum()

movie_id                0
title                   0
overview                3
genres                  0
budget                  0
cast                    0
crew                    0
original_language       0
production_countries    0
production_companies    0
release_date            1
revenue                 0
runtime                 2
vote_average            0
vote_count              0
dtype: int64

In [13]:
movies.dropna(inplace=True)
movies.shape

(4805, 15)

In [14]:
movies.isnull().sum()

movie_id                0
title                   0
overview                0
genres                  0
budget                  0
cast                    0
crew                    0
original_language       0
production_countries    0
production_companies    0
release_date            0
revenue                 0
runtime                 0
vote_average            0
vote_count              0
dtype: int64

#### Checking Duplicate:

In [15]:
movies.duplicated().sum()

0

#### Extracting Values:

In [16]:
def convert(text):
    l=[]
    for i in ast.literal_eval(text):
        l.append(i["name"])
    return l

#### Applying this function

In [17]:
movies.sample()

,movie_id,title,overview,genres,budget,cast,crew,original_language,production_countries,production_companies,release_date,revenue,runtime,vote_average,vote_count
1520,12106,The Quick and the Dead,A mysterious woman comes to compete in a quick...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 37, ""nam...",32000000,"[{""cast_id"": 11, ""character"": ""Ellen \""The Lad...","[{""credit_id"": ""52fe44b69251416c7503e58b"", ""de...",en,"[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}, {""iso_...","[{""name"": ""TriStar Pictures"", ""id"": 559}]",1995-02-09,18552460,107.0,6.3,427

In [18]:
movies["genres"] = movies["genres"].apply(convert)

In [19]:
movies["production_countries"] = movies["production_countries"].apply(convert)

In [20]:
movies["production_companies"] = movies["production_companies"].apply(convert)

In [21]:
movies.head()

,movie_id,title,overview,genres,budget,cast,crew,original_language,production_countries,production_companies,release_date,revenue,runtime,vote_average,vote_count
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]",237000000,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",en,"[United States of America, United Kingdom]","[Ingenious Film Partners, Twentieth Century Fo...",2009-12-10,2787965087,162.0,7.2,11800
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]",300000000,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",en,[United States of America],"[Walt Disney Pictures, Jerry Bruckheimer Films...",2007-05-19,961000000,169.0,6.9,4500
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]",245000000,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",en,"[United Kingdom, United States of America]","[Columbia Pictures, Danjaq, B24]",2015-10-26,880674609,148.0,6.3,4466
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]",250000000,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",en,[United States of America],"[Legendary Pictures, Warner Bros., DC Entertai...",2012-07-16,1084939099,165.0,7.6,9106
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]",260000000,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",en,[United States of America],[Walt Disney Pictures],2012-03-07,284139100,132.0,6.1,2124

#### Extracting Cast:

In [22]:
def convert_cast(text):
    l=[]
    counter=0
    for i in ast.literal_eval(text):
        if counter<3:
            l.append(i["name"])
        else:
            break
        counter+=1
    return l

Applying Function to cast column.
Also making cast dataframe for future use

In [23]:
movies["cast"] = movies["cast"].apply(convert_cast)

#### Function to fetch director from crew data

In [24]:
def fetch_director(text):
    l=[]
    for i in ast.literal_eval(text):
        if i["job"] == "Director":
            l.append(i["name"])
            break
        
    return l

Applying it to crew column. Making Director for future use

In [25]:
movies["crew"] = movies["crew"].apply(fetch_director)

In [26]:

movies['Actor_1'] = movies["cast"].apply(lambda x: x[0] if len(x) > 0 else None)
movies['Actor_2'] = movies["cast"].apply(lambda x: x[1] if len(x) > 1 else None)
movies['Actor_3'] = movies["cast"].apply(lambda x: x[2] if len(x) > 2 else None)

movies = movies.drop("cast", axis=1)

In [27]:
movies['genre_1'] = movies["genres"].apply(lambda x: x[0] if len(x) > 0 else None)
movies['genre_2'] = movies["genres"].apply(lambda x: x[1] if len(x) > 1 else None)
movies['genre_3'] = movies["genres"].apply(lambda x: x[2] if len(x) > 2 else None)
movies['genre_4'] = movies["genres"].apply(lambda x: x[3] if len(x) > 3 else None)
movies['genre_5'] = movies["genres"].apply(lambda x: x[4] if len(x) > 4 else None)

movies = movies.drop("genres", axis=1)

In [28]:
movies['Director'] = movies["crew"].apply(lambda x: x[0] if len(x) > 0 else None)
movies = movies.drop("crew", axis=1)

In [29]:
movies['Country_1'] = movies["production_countries"].apply(lambda x: x[0] if len(x) > 0 else None)
movies['Country_2'] = movies["production_countries"].apply(lambda x: x[1] if len(x) > 1 else None)
movies['Country_3'] = movies["production_countries"].apply(lambda x: x[2] if len(x) > 2 else None)
movies['Country_4'] = movies["production_countries"].apply(lambda x: x[3] if len(x) > 3 else None)
movies['Country_5'] = movies["production_countries"].apply(lambda x: x[4] if len(x) > 4 else None)

movies = movies.drop("production_countries", axis=1)

In [30]:
movies.head()

,movie_id,title,overview,budget,original_language,production_companies,release_date,revenue,runtime,vote_average,vote_count,Actor_1,Actor_2,Actor_3,genre_1,genre_2,genre_3,genre_4,genre_5,Director,Country_1,Country_2,Country_3,Country_4,Country_5
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",237000000,en,"[Ingenious Film Partners, Twentieth Century Fo...",2009-12-10,2787965087,162.0,7.2,11800,Sam Worthington,Zoe Saldana,Sigourney Weaver,Action,Adventure,Fantasy,Science Fiction,None,James Cameron,United States of America,United Kingdom,None,None,None
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",300000000,en,"[Walt Disney Pictures, Jerry Bruckheimer Films...",2007-05-19,961000000,169.0,6.9,4500,Johnny Depp,Orlando Bloom,Keira Knightley,Adventure,Fantasy,Action,None,None,Gore Verbinski,United States of America,None,None,None,None
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,245000000,en,"[Columbia Pictures, Danjaq, B24]",2015-10-26,880674609,148.0,6.3,4466,Daniel Craig,Christoph Waltz,Léa Seydoux,Action,Adventure,Crime,None,None,Sam Mendes,United Kingdom,United States of America,None,None,None
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,250000000,en,"[Legendary Pictures, Warner Bros., DC Entertai...",2012-07-16,1084939099,165.0,7.6,9106,Christian Bale,Michael Caine,Gary Oldman,Action,Crime,Drama,Thriller,None,Christopher Nolan,United States of America,None,None,None,None
4,49529,John Carter,"John Carter is a war-weary, former military ca...",260000000,en,[Walt Disney Pictures],2012-03-07,284139100,132.0,6.1,2124,Taylor Kitsch,Lynn Collins,Samantha Morton,Action,Adventure,Science Fiction,None,None,Andrew Stanton,United States of America,None,None,None,None

In [31]:
temp=movies["production_companies"]

In [32]:
sorted(temp.apply(lambda x: len(x)),reverse=True)

[26,
 25,
 21,
 19,
 18,
 17,
 17,
 17,
 17,
 16,
 16,
 16,
 16,
 16,
 16,
 15,
 15,
 14,
 14,
 14,
 14,
 13,
 13,
 13,
 12,
 12,
 12,
 12,
 12,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 ...]

In [33]:
movies = movies.drop("production_companies", axis=1)

In [34]:
movies=movies[['movie_id', 'title','overview', 'runtime', 'Director',
       'Actor_1', 'Actor_2', 'Actor_3',  'budget','revenue', 'original_language',
       'release_date', 'genre_1', 'genre_2', 'genre_3',
       'genre_4', 'genre_5', 'Country_1', 'Country_2', 'Country_3',
       'Country_4', 'Country_5' ,'vote_average', 'vote_count' ]]

In [35]:
movies=movies[movies["original_language"]=="en"]
movies['original_language']=movies['original_language'].apply(lambda x:"English")

In [36]:
movies.to_csv("Movies.csv",index=False)

In [37]:
directors=movies['Director'].value_counts()[:10].index.tolist()
movies = movies[movies["Director"].isin(directors)]

In [38]:
s = set()
for index, row in movies[["Actor_1", "Actor_2", "Actor_3"]].iterrows():
    # Extract actors' names from each row
    a, b, c = row["Actor_1"], row["Actor_2"], row["Actor_3"]
    # Add actors to the set
    s.add(a)
    s.add(b)
    s.add(c)
s

{'Aaron Eckhart',
 'Adam Beach',
 'Adam Brooks',
 'Adrien Brody',
 'Aidan Gillen',
 'Albert Brooks',
 'Albert Finney',
 'Albert Hall',
 'Alec Baldwin',
 'Alex Pettyfer',
 'Alexa PenaVega',
 'Alfre Woodard',
 'Amber Heard',
 'Amy Adams',
 'Amy Ryan',
 'Andie MacDowell',
 'Andre Braugher',
 'Andrew Dice Clay',
 'Andy García',
 'Andy Serkis',
 'Angela Bassett',
 'Angelina Jolie',
 'Anjelica Huston',
 'Anne Bancroft',
 'Anne Hathaway',
 'Annette Bening',
 'Annie Corley',
 'Anthony Hopkins',
 'Antonio Banderas',
 'Asa Butterfield',
 'Ashley Scott',
 'Barbara Hershey',
 'Barry Pepper',
 'Bee Vang',
 'Ben Kingsley',
 'Benedict Cumberbatch',
 'Benicio del Toro',
 'Billy Crudup',
 'Billy Crystal',
 'Bonnie Bedelia',
 'Brad Pitt',
 'Bradley Cooper',
 'Bruce Willis',
 'Bryce Dallas Howard',
 'Cameron Diaz',
 'Carla Gugino',
 'Carlos Montalbán',
 'Caroline Goodall',
 'Carolyn Saxon',
 'Carrie Snodgress',
 'Cate Blanchett',
 'Catherine Keener',
 "Catherine O'Hara",
 'Catherine Zeta-Jones',
 'Cathy Moriarty',
 'Cayden Boyd',
 'Cedric the Entertainer',
 'Channing Tatum',
 'Charles S. Dutton',
 'Charlie Tahan',
 'Charlie Watts',
 'Chelsea Field',
 'Chiwetel Ejiofor',
 'Christian Bale',
 'Christina Ricci',
 'Christoph Waltz',
 'Christopher Carley',
 'Christopher Walken',
 'Ciarán Hinds',
 'Clea DuVall',
 'Clint Eastwood',
 'Clive Owen',
 'Colin Farrell',
 'Connie Nielsen',
 'Cybill Shepherd',
 'D. L. Hughley',
 'Dakota Fanning',
 'Damon Wayans',
 'Dan Aykroyd',
 'Daniel Craig',
 'Daniel Day-Lewis',
 'Danny Aiello',
 'Danny DeVito',
 'Danny Glover',
 'Danny Trejo',
 'Daryl Sabara',
 'David Duchovny',
 'David Huffman',
 'David Kelly',
 'David Patrick Kelly',
 'David Proval',
 'David Strathairn',
 'Delroy Lindo',
 'Demi Moore',
 'Denholm Elliott',
 'Denzel Washington',
 'Derek Luke',
 'Devon Aoki',
 'Diane Keaton',
 'Dianne Wiest',
 'Diva Gray',
 'Donald Sutherland',
 'Drew Barrymore',
 'Dustin Hoffman',
 'Ed Harris',
 'Edward Norton',
 'Elijah Wood',
 'Ellen Page',
 'Elvis Nolasco',
 'Emily Mortimer',
 'Emily Watson',
 'Eric Bana',
 'Eva Green',
 'Evan Rachel Wood',
 'Ewan McGregor',
 'Felicia Pearson',
 "Frances O'Connor",
 'Frank Langella',
 'François Truffaut',
 'Freddie Highmore',
 'Freddie Jones',
 'Freya Tingley',
 'Gaia Weiss',
 'Geena Davis',
 'Gemma Jones',
 'Gene Hackman',
 'Geoff Pierson',
 'George Clooney',
 'George Hamilton',
 'George McLaren',
 'Giancarlo Esposito',
 'Gina Carano',
 'Glenn Close',
 'Guy Pearce',
 'Gwyneth Paltrow',
 'Haley Joel Osment',
 'Harrison Ford',
 'Harvey Keitel',
 'Helen Hunt',
 'Helena Bonham Carter',
 'Henry Thomas',
 'Hilary Swank',
 'Hugh Jackman',
 'Isaiah Washington',
 'Izabella Scorupco',
 'Jack Nicholson',
 'Jacob Vargas',
 "James D'Arcy",
 'James Spader',
 'Jamie Bell',
 'Jason Biggs',
 'Jason Isaacs',
 'Javier Bardem',
 'Jeff Bridges',
 'Jeff Daniels',
 'Jeff Goldblum',
 'Jeffrey Donovan',
 'Jennifer Lopez',
 'Jennifer Tilly',
 'Jeremy Irons',
 'Jesse Bradford',
 'Jesse Eisenberg',
 'Jessica Alba',
 'Jessica Chastain',
 'Jessica Lange',
 'Jessica Lucas',
 'Jimmy Bennett',
 'Joaquim de Almeida',
 'Joaquin Phoenix',
 'Jodie Foster',
 'Joe Mantegna',
 'Joe Pesci',
 'Joel Edgerton',
 'Joel McHale',
 'John Beck',
 'John Belushi',
 'John Canada Terrell',
 'John Carradine',
 'John Cena',
 'John Cusack',
 'John Goodman',
 'John Larroquette',
 'John Leguizamo',
 'John Lithgow',
 'John Malkovich',
 'John Savage',
 'John Turturro',
 'Johnny Depp',
 'Jolie Vanier',
 'Jonah Hill',
 'Jonathan Ke Quan',
 'Jonathan Rhys Meyers',
 'Jonny Lee Miller',
 'Jordana Brewster',
 'Josh Brolin',
 'Josh Hamilton',
 'Josh Hartnett',
 'Jude Law',
 'Judy Davis',
 'Julia Roberts',
 'Julianne Moore',
 'Karen Allen',
 'Kat Dennings',
 'Kate Beckinsale',
 'Kate Capshaw',
 'Kate Winslet',
 'Kathryn Morris',
 'Kazunari Ninomiya',
 'Keith Richards',
 'Kellan Lutz',
 'Ken Sagoes',
 'Ken Watanabe',
 'Kenneth Branagh',
 'Kevin Bacon',
 'Kevin Spacey',
 'Kim Basinger',
 'Kip Pardue',
 'Kirstie Alley',
 'Kristen Wiig',
 'Krysten Ritter',
 'Kurt Fuller',
 'Kurt Russell',
 'Kyle Gallner',
 'LL Cool J',
 'Lane Smith',
 'Larry David',
 'Laura Dern',
 'Laura Ramsey',
 'Laurence Fishburne',
 'Laz Alonso',
 'Leonardo DiCaprio',
 'Lesley Ann Warren',
 'Levon Helm',
 'Liam McIntyre',
 'Liam Neeson',
 'Lionel Stander',
 'Liza Minnelli',
 'Lou Jacobi',
 'Louise Lasser',
 'Luis Guzmán',
 'Margaret Avery',
 'Margot Robbie',
 'Marianna Hill',
 'Marion Cotillard',
 'Mark Ruffalo',
 'Mark Rylance',
 'Mark Strong',
 'Mark Wahlberg',
 'Martin Landau',
 'Martin Short',
 'Mary Elizabeth Mastrantonio',
 'Mason Cook',
 'Matt Damon',
 'Matthew McConaughey',
 'Matthew Modine',
 'Max von Sydow',
 'Mel Gibson',
 'Meryl Streep',
 'Mia Farrow',
 'Mia Wasikowska',
 'Michael Douglas',
 'Michael Ealy',
 'Michael Fassbender',
 'Michael Keaton',
 'Michael Moriarty',
 'Michael Rooker',
 'Michelle Pfeiffer',
 'Michelle Rodriguez',
 'Mick Jagger',
 'Mickey Rourke',
 'Milla Jovovich',
 'Mira Sorvino',
 'Miranda Otto',
 'Morgan Freeman',
 'Naomi Watts',
 'Natasha Lyonne',
 'Ned Beatty',
 'Nick Nolte',
 'Nicky Katt',
 'Nicolas Cage',
 'Nigel Hawthorne',
 'Noomi Rapace',
 'Orlando Bloom',
 'Ossie Davis',
 'Owen Wilson',
 'Patricia Arquette',
 'Paul Freeman',
 'Paul Newman',
 'Pete Postlethwaite',
 'Peter Gallagher',
 'Philip Seymour Hoffman',
 'Priscilla Presley',
 'Quentin Tarantino',
 'Rachel McAdams',
 'Ralph Fiennes',
 'Ray Allen',
 'Ray Liotta',
 'Rebecca Hall',
 'Richard Dreyfuss',
 'Rick Danko',
 'Robbie Robertson',
 'Robert De Niro',
 'Robert Englund',
 'Robert MacNaughton',
 'Robert Sean Leonard',
 'Robert Shaw',
 'Robin Williams',
 'Rooney Mara',
 'Rosario Dawson',
 'Rowan Blanchard',
 'Roy Scheider',
 'Ruby Barnhill',
 'Ruby Dee',
 'Rupert Friend',
 'Russell Crowe',
 'Rutger Hauer',
 'Ryan Phillippe',
 'Sacha Baron Cohen',
 'Saffron Burrows',
 'Sally Field',
 'Sally Hawkins',
 'Salma Hayek',
 'Sam Neill',
 'Sam Robards',
 'Samantha Morton',
 'Samuel L. Jackson',
 'Sarah Jessica Parker',
 'Savion Glover',
 'Scarlett Johansson',
 'Scott Bakula',
 'Sean Connery',
 'Sean Penn',
 'Sean Young',
 'Sharon Stone',
 'Shia LaBeouf',
 'Sienna Miller',
 'Sigourney Weaver',
 'Spike Lee',
 'Stanley Tucci',
 'Stellan Skarsgård',
 'Steve Harvey',
 'Steven Strait',
 'Sylvester Stallone',
 'Taylor Dooley',
 'Taylor Lautner',
 'Tencho Gyalpo',
 'Tenzin Thuthob Tsarong',
 'Terence Stamp',
 'Teri Garr',
 'Theresa Randle',
 'Thomas Jane',
 'Til Schweiger',
 'Tim Robbins',
 'Tim Roth',
 'Tobey Maguire',
 'Toby Kebbell',
 'Tom Cruise',
 'Tom Hanks',
 'Tom Hiddleston',
 'Tom Skerritt',
 'Tommy Davidson',
 'Tommy Lee Jones',
 'Tommy Redmond Hicks',
 'Tony Kgoroge',
 'Tony Roberts',
 'Tracey Ullman',
 'Tracy Camilla Johns',
 'Tsewang Migyur Khangsar',
 'Tsuyoshi Ihara',
 'Tuesday Knight',
 'Téa Leoni',
 'Val Kilmer',
 'Verna Bloom',
 'Veronica Cartwright',
 'Vic Morrow',
 'Viggo Mortensen',
 'Vin Diesel',
 'Vincent Piazza',
 'Ving Rhames',
 'Wayne Newton',
 'Wesley Snipes',
 'Whoopi Goldberg',
 'Willem Dafoe',
 'William Atherton',
 'Winona Ryder',
 'Woody Allen',
 'Yvonne Zima',
 'Zaraah Abrahams',
 'Zoë Bell'}

In [39]:
s = set()
for index, row in movies[["Country_1", "Country_2", "Country_3","Country_4","Country_5"]].iterrows():
    # Extract actors' names from each row
    a, b, c,d,e = row["Country_1"],row["Country_2"],row["Country_3"],row["Country_4"],row["Country_5"]
    # Add actors to the set
    s.add(a)
    s.add(b)
    s.add(c)
    s.add(d)
    s.add(e)
s

{'Australia',
 'Canada',
 'Finland',
 'France',
 'Germany',
 'Hong Kong',
 'India',
 'Ireland',
 'Italy',
 'Japan',
 'Luxembourg',
 'Morocco',
 'Netherlands',
 'New Zealand',
 None,
 'Russia',
 'Spain',
 'United Arab Emirates',
 'United Kingdom',
 'United States of America'}

In [40]:
movies.to_csv("Movies_less.csv",index=False)